import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Button,
  Alert,
  TextInput,
  TouchableWithoutFeedback,
  TouchableNativeFeedback,
  TouchableHighlight,
  TouchableOpacity,
  TabBarIOS,
  ImageBackground,
  Dimensions,
  Animated,
  Easing,
  Image,
  AppState
} from 'react-native';
import {connect} from 'react-redux'
import styles from '../../appStyle/styleSheet.js'
import * as actions from '../actions'
import { NotificationsAndroid } from 'react-native-notifications'
import RNCalendarEvents from 'react-native-calendar-events';
import RNAlarm from 'react-native-alarm';
import * as Progress from 'react-native-progress'


const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});


class Timer extends Component<{}> {
  constructor(props){
    super(props)
    this.state={
      time:this.props.timerTime,
      shownTime:this.props.counter,
      backgroundColor:'white',
      timers:[],
      paused:true,
      stoped:true,
      notification:null,
      appState: AppState.currentState,
      
      
    }
    

    var started = new Date
    this.springValue= new Animated.Value(0.3)
    RNCalendarEvents.authorizationStatus().then((promise)=>{console.log( "1" + promise )})
    RNCalendarEvents.authorizeEventStore().then((promise)=>{console.log( "2" + promise )})
    RNCalendarEvents.findCalendars().then((promise)=>{console.log( "list = > " + promise )})
    RNAlarm.initAlarm(null)
    RNAlarm.setAlarm("Meeting",'hi','','',()=>{},()=>{})
}

  componentDidMount(){
    this.spring()
    AppState.addEventListener('change', this._handleAppStateChange);
    
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this._handleAppStateChange);
    this.pauseTimer()
  }

  _handleAppStateChange = (nextAppState) => {
    this.setState({appState: nextAppState});
    if (nextAppState=="background"){
      this.onPause()
    }
    else if (nextAppState == "active"){
      this.onResume()
    }
  }


  onPause(){
    
    this.props.inBackground()
    this.pauseTimer()
    this.setState({notification:NotificationsAndroid.localNotification({
      title: "Local notification",
      body: "This notification was generated by the app!",
      extra: "data",
      category: "interactiveNotification"
    })})
    // this.props.paused()
    console.log('1'+this.props.wasInBackground + this.props.startedValue)
    
  }

  onResume(){
    if (this.props.wasInBackground && this.props.startedValue){
      this.startTimer(this.props.counter)
      this.props.inForeground()
      
    }
    console.log('1'+this.props.wasInBackground + this.props.startedValue)
  }
  

  spring () {
    this.springValue.setValue(0.985)
    Animated.spring(
      this.springValue,
      {
        toValue: 1,
        // friction: 4,
        velocity:0,
        // tension:5,
        speed:10,
        bounciness:3
      }
    ).start(() => {
      if(this.props.startedValue)
      this.spring2()
    })
  }



  spring2(){

    this.springValue.setValue(1)
    Animated.spring(
      this.springValue,
      {
        toValue: 0.985,
        friction: 4,
        velocity:0,
        tension:3
      }
    ).start(() => this.spring())

  }
  // componentWillReceiveProps(myprops){
  //   if (props.newTime - this.props.time != 0 && this.props.changedDuringTiming){
  //     this.startTimer()
  //   }
  // }


  gettime(){
    this.setState({ time:this.props.timerTime })
  }

  


  startTimer(time){
    
    // this.props.inForeground()
    this.spring2()
    this.props.started();
    console.log(this.props.wasInBackground)
    if (!this.props.wasInBackground)
    this.props.disableWhenStarted()

    //   this.notif("Your egg is Ready To eat")
    // this.props.presetCounter(180)
    // console.log(this.props.timerTime)
    // var time=this.state.time
    // this.setState({shownTime : this.state.time})
    this.setState({backgroundColor:'white'})
    for(timer in this.state.timers) clearTimeout(this.state.timers[timer])
    this.state.timers=[]
    var counter=time; //this.props.counter
    var a=setInterval(()=>{
      counter--
      this.props.decCounter()
      if (counter == 0) this.props.calculateLastProgressNumber()
      else this.props.calculateProgressNumber()
      // console.log(this.state.shownTime)
      if (counter <=0) {clearInterval(a);this.setState({ backgroundColor : 'rgb(255,255,60)' , paused:true, shownTime:0}); Alert.alert("Your Egg is ready to eat");this.stopTimer();this.props.calculateTime();this.props.stoped()}
      else this.setState((ps)=>{return({ shownTime:ps.shownTime -1 })}) 
    
      
    } , 1000)
    this.state.timers.push(a)
    //this.setState({backgroundColor:"green"})
}
  

  startOrStopIcon(){
    if (this.props.startedValue){
      return(<Image source={require('../../statics/stop.png')} style={{width:50,height:50}} resizeMode={'contain'}/>
      )
    }
    else 
    return(<Image source={require('../../statics/play-button.png')} style={{width:50,height:50}} resizeMode={'contain'}/>
  )
  }
  

  pauseTimer(){
    for(timer in this.state.timers) clearInterval( this.state.timers[timer] )

  }

  stopTimer(){
    if (this.state.notification)
      NotificationsAndroid.cancelLocalNotification(this.state.notification);
    for(timer in this.state.timers) clearInterval( this.state.timers[timer] )
    this.setState({shownTime:this.props.timerTime}) 
    this.setState({paused:true,stoped:true, backgroundColor:'white'})   
    this.props.enableWhenStoped()
    this.props.stoped()
    this.props.calculateTime()
  }

  showStop(){
    if (! this.state.stoped){
    return(
      <TouchableOpacity onPress = {()=>{this.stopTimer()}}>
      <View style={{borderColor:'white', borderWidth:2, backgroundColor:'#66a5ad', width:50, height:50, alignItems:'center', justifyContent:'center', borderRadius:50}}>
        <Text style={{color:'white'}}> اتمام </Text>
      </View>
    </TouchableOpacity>)
    }
    

    else return 
  }

  render() {
    
    // if ( this.props.newTime - this.props.time != 0 ) {this.startTimer(0)}
    var timeee = this.state.stoped ? ("0"+Math.trunc(this.props.timerTime%60)).slice(-2) : ("0"+Math.trunc(this.state.shownTime%60)).slice(-2) 
    return (
      
      <View style={{alignItems:'center', justifyContent:'center'}}>
      <Text>{this.props.counter}</Text>
      
      <ImageBackground resizeMode={'contain'} source={require('../../statics/egg_main.png')} style={{marginLeft:10,marginTop:20,paddingTop:20, justifyContent:'flex-end', alignItems:'center',  width:  250, height:250}}>
          {/* <Text style={{fontSize:35, fontFamily:'main', marginTop:20,fontWeight:'100'}}> 7' 47" </Text> */}
         <TouchableOpacity activeOpacity={0.85} onPress={()=>{
           if (!this.props.startedValue)
           {this.startTimer(this.props.counter)}
            else if (this.props.startedValue)
            {this.stopTimer()}
          }
           
           
           }>

           <Progress.Pie size={115} progress={this.props.progressNumber} style={{marginBottom:60}} color={"#ffb300"} borderColor={"#ffca28"} unfilledColor={"#ffcc50"}>
           <Text>start</Text>
           </Progress.Pie>
           

          </TouchableOpacity>
       </ImageBackground>
       

        
      {/* <View style={{ alignContent:'center', justifyContent:'center'}}>

        <View style={{flexDirection:'row', alignItems:'center', justifyContent:'center'}}>
        <TouchableOpacity onPress={()=>{
          if (this.state.paused){
            this.setState({ paused:false }) 
            if ( this.state.shownTime < 1 ) {this.startTimer(this.props.timerTime); this.setState({shownTime:this.props.timerTime})} //restart
            else if (this.state.stoped){this.startTimer(this.props.timerTime); this.setState({shownTime:this.props.timerTime, stoped:false})}
            else {this.startTimer(this.state.shownTime)} //pause
          }
          else if (!this.state.paused){
            this.setState({paused:true})
            this.pauseTimer()
          }
          }}>
        <View style={{borderRadius:75,borderColor:'white', borderWidth:2 , backgroundColor:'#66a5ad', width:150, height:150, alignItems:'center', justifyContent:'center'}}>
          <Text style={{color:'white'}}> {this.state.paused ? 'شروع' : 'توقف'} </Text>
        </View>
        </TouchableOpacity>

        
        </View>

        <View style={{flexDirection:'row'}}>

          <View style={{width:100, height:50, alignItems:'center', justifyContent:'center'}}>
          </View>
        

          {this.showStop()}
        
        
          <View style={{width:150, height:50, alignItems:'center', justifyContent:'center'}}>
          </View>
          <View style={{width:150, height:50, alignItems:'center', justifyContent:'center'}}>
            <Text style={{color:'white'}}></Text>
          </View>
        </View>
        
      </View>
       */}


      </View>
    );
  }
}


//rgb(255,0,0)
//rgb(200, 0, 50)
//rgb(150,0,100)
//rgb(100, 0, 150)
//rgb(50, 0, 200)
//rgb(0,0,250)


const mapStateToProps= state =>{
  return { 
    time:state.time ,
    counter : state.counter,
    newTime : state.newTime,
    changeDuringTiming : state.changedDuringTiming,
    startedValue : state.startedValue,
    wasInBackground : state.wasInBackground,
    progressNumber: state.progressNumber
    
  }
}

export default connect(mapStateToProps, actions)(Timer)

